import * as Schema from "effect/Schema"
import { EntityId, IsoDateTimeString } from "./node.js"
import { RelationDefinition } from "./relation-definition.js"
import { Tag } from "./tag.js"

// Phase 7 (plan §"Phased delivery": "Workouts + additional gatekeepers + optional blueprints...
// HealthKit import as typed graph pages (proves graph generality, no new mechanism)") — the
// domain shapes a native `HKWorkout` import maps onto. See `docs/workouts-decisions.md` for the
// full design rationale (HealthKit-data-model-mapping decision #1); this file only carries the
// resulting schemas/constants.
//
// **Why not `BASE_TAGS`** (task's decision point 1: "seeded per-workspace, or promoted to
// BASE_TAGS/builtin — decide and justify"): `tag.ts`'s 8 `BASE_TAGS` are a closed, cross-language-
// tested contract — `tag.test.ts#"has exactly 8 Base Tags"`, `graph-service.test.ts`, and the
// Swift↔TS fixture round trip (`EntityDecodingTests.swift#testBaseTagsFixtureMatchesPackageConstant`,
// generated by `native/AthenaeumDomain/scripts/generate-fixtures.ts`) all assert that exact count
// and set. `BASE_TAGS` are also, per the plan's own text, the universal entity vocabulary every
// workspace needs regardless of what it's used for (Person/Organization/Company/Event/Place/Area/
// Project/Task) — Workout/Strength/Cardio/Exercise/Set/Split is a single *feature's* vocabulary,
// named in the plan's Context section in a different sentence, not amended into that enumerated
// list. Widening `BASE_TAGS` to 14 would (a) break that tested invariant for every existing workspace
// and test fixture and (b) unconditionally clutter every workspace — including ones that never import
// a workout — with 6 rows it will never use, forever (Base Tags are seeded once, at workspace
// construction, for every workspace: `seed-base-tags.ts`).
//
// So: a **separate, parallel constant** (`WORKOUT_TAGS`/`WORKOUT_RELATION_DEFINITIONS`), with the
// identical "fixed nil-pattern UUID, `builtin: true`, ship with the app" shape `tag.ts`'s own
// header comment documents for `BASE_TAGS` — Enchiridion's own precedent for this *exact* tag set
// agrees: `WorkoutModule.manifest` (`apps/enchiridion/Sources/EnchiridionCore/WorkoutModule.swift`)
// marks every one of these six supertags `isBuiltIn: true` (preventing user rename/delete of a
// tag the import pipeline depends on referencing by fixed id) while keeping them in their own
// module manifest, entirely separate from Enchiridion's base entity tags — the same two-axis
// split (immutable, but not universal) this file makes. Seeded **lazily, idempotently, per-workspace**
// on first `importWorkout` call (`workouts-service-live.ts#ensureWorkoutTagsSeeded`), not
// unconditionally at workspace construction — a workspace that never imports a workout never gets these
// rows at all.
export const WorkoutTagIds = {
  Workout: EntityId.make("00000000-0000-0000-0000-000000000101"),
  StrengthWorkout: EntityId.make("00000000-0000-0000-0000-000000000102"),
  CardioWorkout: EntityId.make("00000000-0000-0000-0000-000000000103"),
  StrengthExercise: EntityId.make("00000000-0000-0000-0000-000000000104"),
  StrengthSet: EntityId.make("00000000-0000-0000-0000-000000000105"),
  CardioSplit: EntityId.make("00000000-0000-0000-0000-000000000106")
} as const

/**
 * The 6 fixed Workout tags, mirroring Enchiridion's own `WorkoutModule.manifest` supertag set
 * (`Workout`, `Strength Workout`, `Cardio Workout`, `Strength Exercise`, `Strength Set`,
 * `Cardio Split`) — see this file's header comment for why these are a parallel constant, not an
 * extension of `BASE_TAGS`.
 *
 * `Strength Workout`/`Cardio Workout` declare `Workout` as a DAG parent (`parentIds: [Workout]`)
 * — a node tagged `Strength Workout` is transitively `Workout` via `tagClosure`/`graph_tag_closure`
 * (tag-closure.ts), so `hasTag(Workout)` queries find every workout regardless of kind without the
 * import pipeline needing to assign both tags to one node (contrast with Enchiridion's own
 * `createWorkoutPage`, which DOES assign every field-owning supertag explicitly — necessary there
 * only because Enchiridion ties fields to their *exact* owning supertag; Athenaeum's `Fact` rows
 * (fact.ts) carry no such tag-ownership constraint, so a single leaf-tag assignment suffices here
 * — see `docs/workouts-decisions.md` for the full comparison).
 *
 * `Strength Exercise`/`Strength Set`/`Cardio Split` declare no parent — they are never queried via
 * `hasTag(Workout)` themselves (a Set is not itself a Workout), only reached via the `edges`
 * relations below.
 */
export const WORKOUT_TAGS: ReadonlyArray<Tag> = [
  new Tag({ id: WorkoutTagIds.Workout, name: "Workout", parentIds: [], builtin: true }),
  new Tag({
    id: WorkoutTagIds.StrengthWorkout,
    name: "Strength Workout",
    parentIds: [WorkoutTagIds.Workout],
    builtin: true
  }),
  new Tag({
    id: WorkoutTagIds.CardioWorkout,
    name: "Cardio Workout",
    parentIds: [WorkoutTagIds.Workout],
    builtin: true
  }),
  new Tag({ id: WorkoutTagIds.StrengthExercise, name: "Strength Exercise", parentIds: [], builtin: true }),
  new Tag({ id: WorkoutTagIds.StrengthSet, name: "Strength Set", parentIds: [], builtin: true }),
  new Tag({ id: WorkoutTagIds.CardioSplit, name: "Cardio Split", parentIds: [], builtin: true })
]

export const WorkoutRelationIds = {
  WorkoutExercises: EntityId.make("00000000-0000-0000-0000-000000000111"),
  ExerciseSets: EntityId.make("00000000-0000-0000-0000-000000000112"),
  WorkoutSplits: EntityId.make("00000000-0000-0000-0000-000000000113")
} as const

/**
 * The 3 fixed relations a workout's node subgraph uses — same fixed-id, seeded-once discipline as
 * `WORKOUT_TAGS` above (and the same reason: `createEdge`, graph-service-live.ts, requires the
 * referenced `RelationDefinition` to already exist by id, so the import pipeline needs stable,
 * known ids to create edges against, not ones minted fresh — and therefore random — per workspace by
 * `GraphService.createRelationDefinition`). Mirrors Enchiridion's own `WorkoutModule.Relation`
 * (`workoutExercises`/`exerciseSets`/`workoutSplits`), including its `oneToMany` cardinality for
 * all three — a workout has many exercises, an exercise has many sets, a cardio workout has many
 * splits, and (per relation-definition.ts's `RelationCardinality`) `"one-to-many"` places no cap
 * on the number of outgoing edges from one source node, matching that shape exactly.
 */
export const WORKOUT_RELATION_DEFINITIONS: ReadonlyArray<RelationDefinition> = [
  new RelationDefinition({
    id: WorkoutRelationIds.WorkoutExercises,
    forwardName: "exercises",
    inverseName: "workout",
    sourceTagId: WorkoutTagIds.StrengthWorkout,
    targetTagId: WorkoutTagIds.StrengthExercise,
    cardinality: "one-to-many"
  }),
  new RelationDefinition({
    id: WorkoutRelationIds.ExerciseSets,
    forwardName: "sets",
    inverseName: "exercise",
    sourceTagId: WorkoutTagIds.StrengthExercise,
    targetTagId: WorkoutTagIds.StrengthSet,
    cardinality: "one-to-many"
  }),
  new RelationDefinition({
    id: WorkoutRelationIds.WorkoutSplits,
    forwardName: "splits",
    inverseName: "workout",
    sourceTagId: WorkoutTagIds.CardioWorkout,
    targetTagId: WorkoutTagIds.CardioSplit,
    cardinality: "one-to-many"
  })
]

/**
 * Stable `Fact.predicateId` strings (fact.ts: "predicateId stable across renames") the import
 * pipeline writes. Plain kebab-case strings, matching this codebase's existing convention
 * (`AddFactInput.json` fixture uses `"status"`; the plan's own Tasks example uses
 * `"due-date"`/`"status"`) — deliberately reusing Enchiridion's own `WorkoutModule` field-id
 * vocabulary almost verbatim (`started-at`, `duration-seconds`, `healthkit-workout-uuid`, …) since
 * that vocabulary is itself a validated, shipped design for this exact problem, not reinvented
 * here for its own sake.
 */
export const WorkoutFactPredicate = {
  // Root `Workout`-tagged node facts (every import, both kinds).
  StartedAt: "started-at",
  CompletedAt: "completed-at",
  DurationSeconds: "duration-seconds",
  Activity: "activity",
  RawActivity: "raw-activity",
  Source: "source",
  SourceWorkoutId: "source-workout-id",
  EnergyKilocalories: "energy-kilocalories",
  AverageHeartRate: "average-heart-rate",
  MaximumHeartRate: "maximum-heart-rate",
  // Strength-specific roll-ups (root node).
  ExerciseCount: "exercise-count",
  SetCount: "set-count",
  TotalVolumeKilograms: "total-volume-kilograms",
  // Cardio-specific roll-ups (root node).
  DistanceMeters: "distance-meters",
  ElevationMeters: "elevation-meters",
  AverageSpeedMetersPerSecond: "average-speed-meters-per-second",
  AveragePaceSecondsPerKilometre: "average-pace-seconds-per-kilometre",
  SplitCount: "split-count",
  // Shared ordinal facts (exercise/set/split nodes).
  Ordinal: "ordinal",
  // Exercise-node facts.
  ExerciseSetCount: "exercise-set-count",
  ExerciseVolumeKilograms: "exercise-volume-kilograms",
  // Set-node facts.
  Repetitions: "repetitions",
  LoadKilograms: "load-kilograms",
  VolumeKilograms: "volume-kilograms",
  Rpe: "rpe",
  SetCompletedAt: "set-completed-at",
  // Split-node facts.
  SplitDistanceMeters: "split-distance-meters",
  SplitDurationSeconds: "split-duration-seconds",
  PaceSecondsPerKilometre: "pace-seconds-per-kilometre"
} as const

/**
 * The activity vocabulary this pipeline recognizes, mapped from `HKWorkoutActivityType`
 * (`HealthKitWorkoutDataSource`, native) or chosen directly by a synthetic/test source. Wider than
 * Enchiridion's own `WorkoutActivity` enum (which only names the handful of activities its
 * *live-capture* watch flow deliberately supports) because a HealthKit *import* pipeline reads
 * arbitrary historical data and must accept every `HKWorkoutActivityType` gracefully — anything
 * not in this literal set maps to `"other"`, with the HealthKit SDK's own raw type name preserved
 * verbatim in the `raw-activity` fact (never dropped), the same "map what you can name, preserve
 * the rest losslessly" discipline `CalendarEventStatus`'s own header comment establishes for a
 * different provider-sourced literal union.
 */
export const WorkoutActivityKind = Schema.Literal(
  "strength-training",
  "running",
  "cycling",
  "walking",
  "hiking",
  "swimming",
  "rowing",
  "elliptical",
  "yoga",
  "hiit",
  "other"
)
export type WorkoutActivityKind = typeof WorkoutActivityKind.Type

/** Which pipeline produced an import — real HealthKit or the synthetic test double. Kept as a
 *  fact on the root node (not just an ambient assumption) so a real workspace's workout history stays
 *  auditable even after fixture/synthetic data is used during development. */
export const WorkoutSource = Schema.Literal("healthkit", "synthetic")
export type WorkoutSource = typeof WorkoutSource.Type

/**
 * The idempotent-import receipt (backend-internal collection, `workout-collections.ts`, plus the
 * `listWorkoutImports` read RPC, `workout-rpc.ts`) — one row per successfully imported `HKWorkout`,
 * keyed by `sourceWorkoutId` (the real `HKWorkout.uuid.uuidString`, or a synthetic source's own
 * stable id). Mirrors Enchiridion's own `workout_import_receipts` table
 * (`WorkoutModule.swift#importWorkout`: "Receipts are an optimisation, not the identity
 * authority... a durable page lets a restarted importer recover safely after a receipt is lost") —
 * same purpose here: a re-run import (the native client retrying after a dropped response, or a
 * user re-triggering a HealthKit sync) with the same `sourceWorkoutId` and the same content is a
 * cheap idempotent no-op (`ImportWorkoutOutput.duplicate: true`), not a duplicate node subgraph.
 *
 * `rootNodeId` is this receipt's one `linkedNodeId`-shaped field — a reference to the `Workout`-
 * tagged node this import created. See `workspace-durable-object.ts`'s `listWorkoutImports` doc
 * comment for why this field gets the same observer-exclusion treatment
 * `CalendarService#hiddenCalendarDerivedNodeIds` already established for `Meeting.linkedNodeId`/
 * `Bookmark.linkedNodeId`, even though nothing makes a workout-imported node hidden today.
 */
export class WorkoutImportReceipt extends Schema.Class<WorkoutImportReceipt>("WorkoutImportReceipt")({
  id: EntityId,
  workspaceId: EntityId,
  sourceWorkoutId: Schema.String.pipe(Schema.minLength(1)),
  source: WorkoutSource,
  payloadHash: Schema.String.pipe(Schema.minLength(1)),
  rootNodeId: EntityId,
  importedAt: IsoDateTimeString
}) {}

// --- Read models: listWorkouts/getWorkout (workout-rpc.ts) ----------------------------------
//
// Domain-extension task item 3's read side. Unlike `CalendarEvent`/`Bookmark`/`Meeting` (each a
// dedicated collection row `listWorkouts`/`getWorkout` could read directly), a Workout has no
// collection row of its own — per this file's header comment, and the plan's own Phase 7 framing
// ("HealthKit import as typed graph pages... no new mechanism"), a workout IS its `nodes`/`facts`/
// `edges` subgraph. These classes are therefore not storage rows but the assembled READ shape a
// `WorkoutsService` implementation (a later stage) reconstructs from `NodesRepository`/
// `GraphService` reads keyed off `WorkoutFactPredicate` — the reverse of `importWorkout`'s own
// `buildRootFacts`/`importWorkoutSubgraph` write path (`workouts-service-live.ts`).
//
// **`nodeId` gets the same observer-exclusion treatment as `WorkoutImportReceipt.rootNodeId`**
// (see that class's own doc comment): it is a `linkedNodeId`-shaped reference to a graph node, so
// a future `WorkoutsService#listWorkouts`/`#getWorkout` implementation MUST run its results
// through the same hidden-node filter `filterHiddenWorkoutImportReceipts`
// (`workspace-durable-object.ts`) already applies to `listWorkoutImports`, even though nothing makes
// a workout-imported node hidden today — the established defensive convention this codebase's
// hard constraints call for, not skipped just because this stage is schema-only.

/** One completed strength set, read back from a `Strength Set`-tagged node's facts
 *  (`WorkoutFactPredicate.Ordinal`/`.Repetitions`/`.LoadKilograms`/`.VolumeKilograms`/`.Rpe`/
 *  `.SetCompletedAt`). `nodeId` is that node's own id — present so a caller (a UI, or a future
 *  agent tool once workouts join that surface) can navigate to it directly via the existing
 *  generic graph RPCs, the same "read model points back at its source node" discipline
 *  `GetMeetingOutput`'s `Speaker`/`TranscriptSegmentRecord` rows establish for their own `id`
 *  fields (meeting-rpc.ts). */
export class WorkoutStrengthSet extends Schema.Class<WorkoutStrengthSet>("WorkoutStrengthSet")({
  nodeId: EntityId,
  ordinal: Schema.Number.pipe(Schema.int(), Schema.greaterThanOrEqualTo(1)),
  repetitions: Schema.Number.pipe(Schema.int(), Schema.nonNegative()),
  loadKilograms: Schema.Number.pipe(Schema.nonNegative()),
  volumeKilograms: Schema.Number.pipe(Schema.nonNegative()),
  rpe: Schema.optional(Schema.Number),
  completedAt: Schema.optional(IsoDateTimeString)
}) {}

/** One exercise within a strength workout, read back from a `Strength Exercise`-tagged node's
 *  facts plus its `sets` relation (`WorkoutRelationIds.ExerciseSets`), sets ordered by
 *  `WorkoutStrengthSet.ordinal`. */
export class WorkoutStrengthExercise extends Schema.Class<WorkoutStrengthExercise>("WorkoutStrengthExercise")({
  nodeId: EntityId,
  ordinal: Schema.Number.pipe(Schema.int(), Schema.greaterThanOrEqualTo(1)),
  name: Schema.String.pipe(Schema.minLength(1)),
  volumeKilograms: Schema.Number.pipe(Schema.nonNegative()),
  sets: Schema.Array(WorkoutStrengthSet)
}) {}

/** One distance/time split within a cardio workout, read back from a `Cardio Split`-tagged
 *  node's facts. May be an empty array on the owning `WorkoutDetail` when the source import had
 *  no lap/segment structure — see `CardioSplitImportInput`'s own doc comment (workout-rpc.ts) for
 *  why that is a common, expected case, not a data-loss bug. */
export class WorkoutCardioSplit extends Schema.Class<WorkoutCardioSplit>("WorkoutCardioSplit")({
  nodeId: EntityId,
  ordinal: Schema.Number.pipe(Schema.int(), Schema.greaterThanOrEqualTo(1)),
  distanceMeters: Schema.Number.pipe(Schema.greaterThan(0)),
  durationSeconds: Schema.Number.pipe(Schema.greaterThan(0)),
  paceSecondsPerKilometre: Schema.optional(Schema.Number),
  averageHeartRate: Schema.optional(Schema.Number),
  energyKilocalories: Schema.optional(Schema.Number)
}) {}

/** `GetWorkoutOutput`'s (workout-rpc.ts) discriminated child-subgraph payload — the read-side
 *  mirror of `WorkoutImportPayload` (workout-rpc.ts), same `kind`-discriminated shape and same
 *  rationale for discriminating on `kind` rather than deriving it from `activity` (see that
 *  type's own doc comment). */
export const WorkoutDetailPayload = Schema.Union(
  Schema.Struct({
    kind: Schema.Literal("strength"),
    exercises: Schema.Array(WorkoutStrengthExercise)
  }),
  Schema.Struct({
    kind: Schema.Literal("cardio"),
    splits: Schema.Array(WorkoutCardioSplit),
    distanceMeters: Schema.optional(Schema.Number),
    elevationMeters: Schema.optional(Schema.Number),
    averageSpeedMetersPerSecond: Schema.optional(Schema.Number),
    averagePaceSecondsPerKilometre: Schema.optional(Schema.Number)
  })
)
export type WorkoutDetailPayload = typeof WorkoutDetailPayload.Type

/** `listWorkouts`' (workout-rpc.ts) per-row shape — every root-node fact EXCEPT the strength/
 *  cardio roll-ups (`WorkoutFactPredicate.ExerciseCount`/`.TotalVolumeKilograms`/
 *  `.DistanceMeters`/etc.) and the child subgraph itself, matching `ListMeetingsOutput`'s
 *  identical "list is lightweight, get is the full aggregate" split (meeting-rpc.ts's own doc
 *  comment) — a workout-history list view needs only enough to render one row per workout, not
 *  every exercise/set/split; a caller wanting those calls `getWorkout`. `kind` says which of
 *  `Strength Workout`/`Cardio Workout` this root node is tagged (workout.ts's `WorkoutTagIds`)
 *  without the caller needing to inspect tags directly. */
export class WorkoutSummary extends Schema.Class<WorkoutSummary>("WorkoutSummary")({
  nodeId: EntityId,
  workspaceId: EntityId,
  sourceWorkoutId: Schema.String.pipe(Schema.minLength(1)),
  source: WorkoutSource,
  kind: Schema.Literal("strength", "cardio"),
  activity: WorkoutActivityKind,
  rawActivity: Schema.optional(Schema.String),
  startedAt: IsoDateTimeString,
  completedAt: IsoDateTimeString,
  durationSeconds: Schema.Number.pipe(Schema.nonNegative()),
  energyKilocalories: Schema.optional(Schema.Number),
  averageHeartRate: Schema.optional(Schema.Number),
  maximumHeartRate: Schema.optional(Schema.Number)
}) {}

/** `getWorkout`'s (workout-rpc.ts) full aggregate — every root-node fact plus the reconstructed
 *  exercise/set or split subgraph, mirroring `GetMeetingOutput`'s "one aggregate read, not
 *  several round trips" shape (meeting-rpc.ts's own doc comment). Deliberately NOT built by
 *  composing `WorkoutSummary` (e.g. `extends WorkoutSummary`'s fields) — this codebase's existing
 *  RPC files consistently declare each `Schema.Class`'s fields directly rather than compose
 *  schemas together (compare `StartMeetingOutput`/`GetMeetingOutput`, which share no base class
 *  despite both carrying a `Meeting`), so this follows the same flat-declaration convention
 *  rather than introducing a new composition pattern for one entity. */
export class WorkoutDetail extends Schema.Class<WorkoutDetail>("WorkoutDetail")({
  nodeId: EntityId,
  workspaceId: EntityId,
  sourceWorkoutId: Schema.String.pipe(Schema.minLength(1)),
  source: WorkoutSource,
  activity: WorkoutActivityKind,
  rawActivity: Schema.optional(Schema.String),
  startedAt: IsoDateTimeString,
  completedAt: IsoDateTimeString,
  durationSeconds: Schema.Number.pipe(Schema.nonNegative()),
  energyKilocalories: Schema.optional(Schema.Number),
  averageHeartRate: Schema.optional(Schema.Number),
  maximumHeartRate: Schema.optional(Schema.Number),
  payload: WorkoutDetailPayload
}) {}
