import * as stylex from "@stylexjs/stylex";
import { colors, fonts, radii, shadows, sizes, space, zIndex } from "./tokens.stylex";

const spin = stylex.keyframes({
	to: {
		transform: "rotate(360deg)",
	},
});

export const shell = stylex.create({
	loadingShell: {
		display: "grid",
		minHeight: "100vh",
		placeItems: "center",
		gap: space.six,
		color: colors.muted,
	},
	loadingMark: {
		width: "32px",
		height: "32px",
		borderWidth: "2px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderTopColor: colors.primary,
		borderRadius: "50%",
		animationName: spin,
		animationDuration: "0.8s",
		animationTimingFunction: "linear",
		animationIterationCount: "infinite",
	},
	appShell: {
		display: "grid",
		gridTemplateColumns: "260px minmax(0, 1fr) 360px",
		minHeight: "100vh",
		"@media (max-width: 1180px)": {
			gridTemplateColumns: "230px minmax(0, 1fr)",
		},
		"@media (max-width: 760px)": {
			gridTemplateColumns: "1fr",
		},
	},
	sidebar: {
		position: "sticky",
		top: 0,
		height: "100vh",
		overflow: "auto",
		borderRightWidth: "1px",
		borderRightStyle: "solid",
		borderRightColor: colors.border,
		backgroundColor: colors.chrome,
		padding: space.nine,
		"@media (max-width: 760px)": {
			position: "static",
			height: "auto",
			borderRightWidth: "0",
			borderBottomWidth: "1px",
			borderBottomStyle: "solid",
			borderBottomColor: colors.border,
		},
	},
	contextRail: {
		height: "100vh",
		overflow: "auto",
		borderLeftWidth: "1px",
		borderLeftStyle: "solid",
		borderLeftColor: colors.border,
		backgroundColor: colors.chrome,
		padding: space.nine,
		"@media (max-width: 1180px)": {
			gridColumn: "1 / -1",
			height: "auto",
			borderLeftWidth: "0",
			borderTopWidth: "1px",
			borderTopStyle: "solid",
			borderTopColor: colors.border,
			display: "grid",
			gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
			gap: space.six,
		},
	},
	brand: {
		display: "flex",
		alignItems: "center",
		gap: space.five,
		marginBottom: space.nine,
	},
	brandMark: {
		display: "grid",
		width: sizes.controlMd,
		height: sizes.controlMd,
		placeItems: "center",
		borderRadius: radii.control,
		backgroundColor: colors.primary,
		color: colors.bg,
		fontWeight: 750,
	},
	blockText: {
		display: "block",
	},
	mutedText: {
		color: colors.muted,
		fontSize: sizes.textSm,
	},
	controlBase: {
		display: "inline-flex",
		alignItems: "center",
		gap: space.four,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.surfaceRaised,
		color: colors.ink,
		cursor: "pointer",
		textDecoration: "none",
		transitionProperty: "border-color, background-color, color",
		transitionDuration: "160ms",
		transitionTimingFunction: "ease",
		":focus-visible": {
			outline: "none",
			boxShadow: shadows.focus,
		},
	},
	interactiveHover: {
		":hover": {
			borderColor: colors.primary,
			backgroundColor: colors.primarySoft,
		},
	},
	commandButton: {
		width: "100%",
		justifyContent: "space-between",
		marginBottom: space.nine,
		padding: space.five,
	},
	keycap: {
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: "5px",
		paddingTop: "1px",
		paddingRight: "5px",
		paddingBottom: "1px",
		paddingLeft: "5px",
		color: colors.muted,
		fontFamily: fonts.mono,
		fontSize: sizes.textXs,
	},
	stack: {
		display: "grid",
		gap: space.four,
	},
	navItem: {
		justifyContent: "flex-start",
		width: "100%",
		paddingTop: space.four,
		paddingRight: space.five,
		paddingBottom: space.four,
		paddingLeft: space.five,
		textAlign: "left",
	},
	navItemActive: {
		borderColor: colors.primary,
		backgroundColor: colors.primarySoft,
		color: colors.primaryHover,
	},
	sidebarSection: {
		display: "grid",
		gap: space.four,
		marginTop: space.ten,
	},
	sectionHeading: {
		margin: 0,
		fontSize: sizes.textMd,
		fontWeight: 700,
	},
	miniAppLink: {
		display: "flex",
		justifyContent: "space-between",
		paddingTop: space.four,
		paddingRight: space.five,
		paddingBottom: space.four,
		paddingLeft: space.five,
	},
	workspace: {
		display: "grid",
		gridTemplateRows: "auto auto minmax(0, 1fr)",
		minWidth: 0,
		backgroundColor: colors.bg,
	},
	workspaceHeader: {
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "space-between",
		gap: space.eight,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
		paddingTop: space.ten,
		paddingRight: space.twelve,
		paddingBottom: space.nine,
		paddingLeft: space.twelve,
		"@media (max-width: 760px)": {
			display: "grid",
			paddingTop: space.nine,
			paddingRight: space.nine,
			paddingBottom: space.nine,
			paddingLeft: space.nine,
		},
	},
	pageTitle: {
		marginTop: space.three,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		fontSize: sizes.textXl,
		lineHeight: 1.15,
		letterSpacing: 0,
	},
	dateControls: {
		display: "inline-flex",
		alignItems: "center",
		gap: space.three,
		color: colors.muted,
		fontFamily: fonts.mono,
		fontSize: sizes.textSm,
	},
	iconButton: {
		width: sizes.controlSm,
		height: sizes.controlSm,
		justifyContent: "center",
		padding: 0,
	},
	saveState: {
		display: "inline-flex",
		alignItems: "center",
		gap: space.four,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.pill,
		paddingTop: space.three,
		paddingRight: space.five,
		paddingBottom: space.three,
		paddingLeft: space.five,
		color: colors.muted,
		fontSize: sizes.textSm,
	},
	saveSaving: {
		color: colors.warning,
	},
	saveSaved: {
		color: colors.success,
	},
	saveError: {
		color: colors.danger,
	},
	editorToolbar: {
		display: "flex",
		flexWrap: "wrap",
		gap: space.four,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
		paddingTop: space.five,
		paddingRight: space.twelve,
		paddingBottom: space.five,
		paddingLeft: space.twelve,
		"@media (max-width: 760px)": {
			paddingRight: space.nine,
			paddingLeft: space.nine,
		},
	},
	toolbarButton: {
		paddingTop: space.three,
		paddingRight: space.five,
		paddingBottom: space.three,
		paddingLeft: space.five,
		fontSize: sizes.textMd,
	},
	editorPanel: {
		minWidth: 0,
		overflow: "auto",
		paddingTop: space.thirteen,
		paddingRight: space.twelve,
		paddingBottom: "60px",
		paddingLeft: space.twelve,
		"@media (max-width: 760px)": {
			paddingRight: space.nine,
			paddingLeft: space.nine,
		},
	},
	panel: {
		display: "grid",
		gap: space.six,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.panel,
		backgroundColor: colors.surfaceRaised,
		padding: space.seven,
		marginBottom: space.six,
	},
	panelHeading: {
		display: "flex",
		alignItems: "center",
		gap: space.four,
	},
	field: {
		width: "100%",
		minWidth: 0,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.bg,
		paddingTop: space.four,
		paddingRight: space.five,
		paddingBottom: space.four,
		paddingLeft: space.five,
		color: colors.ink,
		"::placeholder": {
			color: colors.muted,
		},
		":focus": {
			outline: "none",
			boxShadow: shadows.focus,
		},
	},
	resourceRow: {
		display: "grid",
		gap: space.one,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		padding: space.four,
		color: colors.ink,
		textDecoration: "none",
		":focus-visible": {
			outline: "none",
			boxShadow: shadows.focus,
		},
	},
	rowMeta: {
		color: colors.muted,
		fontSize: sizes.textSm,
	},
	auditRow: {
		gap: space.two,
	},
	auditHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: space.four,
		minWidth: 0,
	},
	auditTitle: {
		minWidth: 0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	auditStatus: {
		flexShrink: 0,
		maxWidth: "58%",
		overflow: "hidden",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.pill,
		paddingTop: space.one,
		paddingRight: space.four,
		paddingBottom: space.one,
		paddingLeft: space.four,
		color: colors.muted,
		fontSize: sizes.textXs,
		lineHeight: 1.45,
		textOverflow: "ellipsis",
		textTransform: "capitalize",
		whiteSpace: "nowrap",
	},
	auditStatusSuccess: {
		borderColor: "oklch(0.82 0.055 150)",
		backgroundColor: "oklch(0.96 0.024 150)",
		color: colors.success,
	},
	auditStatusWarning: {
		borderColor: "oklch(0.84 0.09 75)",
		backgroundColor: "oklch(0.97 0.036 75)",
		color: "oklch(0.43 0.1 75)",
	},
	auditStatusDanger: {
		borderColor: "oklch(0.82 0.07 28)",
		backgroundColor: "oklch(0.96 0.025 28)",
		color: colors.danger,
	},
	auditSummary: {
		display: "-webkit-box",
		overflow: "hidden",
		color: colors.ink,
		fontSize: sizes.textSm,
		lineHeight: 1.35,
		WebkitBoxOrient: "vertical",
		WebkitLineClamp: 2,
	},
	inlineForm: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) minmax(0, 0.8fr) auto",
		gap: space.three,
	},
	inlineFormSingle: {
		gridTemplateColumns: "minmax(0, 1fr) auto",
	},
	primaryIconButton: {
		width: sizes.controlLg,
		justifyContent: "center",
		padding: 0,
		backgroundColor: colors.primary,
		color: colors.bg,
		":hover": {
			backgroundColor: colors.primaryHover,
		},
	},
	primaryTextButton: {
		justifyContent: "center",
		paddingTop: space.three,
		paddingRight: space.five,
		paddingBottom: space.three,
		paddingLeft: space.five,
		backgroundColor: colors.primary,
		color: colors.bg,
		fontSize: sizes.textMd,
		":hover": {
			backgroundColor: colors.primaryHover,
		},
		":disabled": {
			cursor: "wait",
			opacity: 0.72,
		},
	},
	kanbanPreview: {
		display: "grid",
		gap: space.five,
	},
	kanbanColumns: {
		display: "grid",
		gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
		gap: space.four,
		"@media (max-width: 760px)": {
			gridTemplateColumns: "1fr",
		},
	},
	kanbanColumn: {
		minWidth: 0,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.surface,
		padding: space.four,
	},
	kanbanColumnTitle: {
		display: "block",
		marginBottom: space.three,
		fontSize: sizes.textSm,
	},
	kanbanCard: {
		display: "block",
		overflow: "hidden",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.tag,
		backgroundColor: colors.bg,
		padding: space.three,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: sizes.textSm,
	},
	paletteBackdrop: {
		position: "fixed",
		inset: 0,
		zIndex: zIndex.modalBackdrop,
		display: "grid",
		alignItems: "start",
		justifyItems: "center",
		backgroundColor: colors.backdrop,
		paddingTop: "12vh",
		paddingRight: space.eight,
		paddingBottom: space.eight,
		paddingLeft: space.eight,
	},
	palette: {
		width: "min(680px, 100%)",
		overflow: "hidden",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.modal,
		backgroundColor: colors.bg,
		boxShadow: shadows.popover,
	},
	paletteInput: {
		display: "flex",
		alignItems: "center",
		gap: space.five,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
		padding: space.six,
	},
	paletteField: {
		borderWidth: "0",
		paddingTop: space.two,
		paddingRight: 0,
		paddingBottom: space.two,
		paddingLeft: 0,
	},
	paletteList: {
		display: "grid",
		maxHeight: "420px",
		overflow: "auto",
		padding: space.four,
	},
	paletteButton: {
		display: "grid",
		gridTemplateColumns: "auto minmax(0, 1fr) auto",
		width: "100%",
		borderColor: "transparent",
		padding: space.five,
		textAlign: "left",
	},
	paletteLabel: {
		display: "grid",
		gap: space.one,
	},
	paletteMeta: {
		display: "block",
		color: colors.muted,
		fontSize: sizes.textSm,
		fontStyle: "normal",
	},
	agentPanel: {
		display: "grid",
		gap: space.four,
	},
	agentTranscript: {
		display: "grid",
		gap: space.three,
		maxHeight: "240px",
		overflow: "auto",
		paddingRight: space.one,
	},
	agentEmpty: {
		display: "inline-flex",
		alignItems: "center",
		gap: space.three,
		color: colors.muted,
		fontSize: sizes.textSm,
	},
	agentMessage: {
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
		borderLeftWidth: "2px",
		borderLeftStyle: "solid",
		borderLeftColor: colors.border,
		paddingTop: space.two,
		paddingRight: 0,
		paddingBottom: space.two,
		paddingLeft: space.four,
		color: colors.ink,
		fontSize: sizes.textSm,
		lineHeight: 1.45,
	},
	agentUserMessage: {
		borderLeftColor: colors.primary,
		color: colors.primaryHover,
	},
	agentSystemMessage: {
		borderLeftColor: colors.danger,
		color: colors.danger,
	},
	agentTextArea: {
		minHeight: "84px",
		resize: "vertical",
		lineHeight: 1.4,
	},
	agentActions: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
		gap: space.three,
	},
	agentLink: {
		color: colors.primary,
		fontWeight: 650,
		textDecoration: "none",
		":focus-visible": {
			outline: "none",
			boxShadow: shadows.focus,
		},
	},
	inlineCode: {
		fontFamily: fonts.mono,
		fontSize: sizes.textXs,
	},
});
