import * as stylex from "@stylexjs/stylex";
import { colors, fonts, motion, radii, shadows, sizes, space, zIndex } from "./tokens.stylex";

const spin = stylex.keyframes({
	to: {
		transform: "rotate(360deg)",
	},
});

export const shell = stylex.create({
	loadingShell: {
		display: "grid",
		minHeight: "100vh",
		placeItems: "center",
		gap: space.six,
		color: colors.muted,
		padding: space.nine,
	},
	loadingMark: {
		width: "32px",
		height: "32px",
		borderWidth: "2px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderTopColor: colors.primary,
		borderRadius: "50%",
		animationName: spin,
		animationDuration: "0.8s",
		animationTimingFunction: "linear",
		animationIterationCount: "infinite",
		"@media (prefers-reduced-motion: reduce)": {
			animationName: "none",
		},
	},
	loadingPanel: {
		display: "grid",
		justifyItems: "center",
		gap: space.five,
		maxWidth: "420px",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.panel,
		backgroundColor: colors.surfaceRaised,
		padding: space.ten,
		textAlign: "center",
	},
	loadingErrorMark: {
		display: "grid",
		width: sizes.controlMd,
		height: sizes.controlMd,
		placeItems: "center",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.dangerBorder,
		borderRadius: radii.control,
		backgroundColor: colors.dangerSoft,
		color: colors.danger,
	},
	loadingCopy: {
		display: "grid",
		gap: space.three,
	},
	loadingTitle: {
		margin: 0,
		color: colors.ink,
		fontSize: sizes.textLg,
		lineHeight: 1.2,
		letterSpacing: 0,
	},
	loadingMessage: {
		margin: 0,
		color: colors.muted,
		fontSize: sizes.textMd,
		lineHeight: 1.45,
	},
	appShell: {
		display: "grid",
		gridTemplateColumns: "260px minmax(0, 1fr)",
		minHeight: "100vh",
		"@media (max-width: 1180px)": {
			gridTemplateColumns: "230px minmax(0, 1fr)",
		},
		"@media (max-width: 760px)": {
			gridTemplateColumns: "1fr",
		},
	},
	appShellWithPanel: {
		gridTemplateColumns: "260px minmax(0, 1fr) minmax(360px, 520px)",
		"@media (max-width: 1180px)": {
			gridTemplateColumns: "230px minmax(0, 1fr)",
		},
		"@media (max-width: 760px)": {
			gridTemplateColumns: "1fr",
		},
	},
	sidebar: {
		position: "sticky",
		top: 0,
		height: "100vh",
		overflow: "auto",
		borderRightWidth: "1px",
		borderRightStyle: "solid",
		borderRightColor: colors.border,
		backgroundColor: colors.chrome,
		padding: space.nine,
		"@media (max-width: 760px)": {
			position: "static",
			height: "auto",
			borderRightWidth: "0",
			borderBottomWidth: "1px",
			borderBottomStyle: "solid",
			borderBottomColor: colors.border,
		},
	},
	contextRail: {
		height: "100vh",
		overflow: "auto",
		borderLeftWidth: "1px",
		borderLeftStyle: "solid",
		borderLeftColor: colors.border,
		backgroundColor: colors.chrome,
		padding: space.nine,
		"@media (max-width: 1180px)": {
			gridColumn: "1 / -1",
			height: "auto",
			borderLeftWidth: "0",
			borderTopWidth: "1px",
			borderTopStyle: "solid",
			borderTopColor: colors.border,
			display: "grid",
			gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
			gap: space.six,
		},
	},
	brand: {
		display: "flex",
		alignItems: "center",
		gap: space.five,
		marginBottom: space.nine,
	},
	brandMark: {
		display: "grid",
		width: sizes.controlMd,
		height: sizes.controlMd,
		placeItems: "center",
		borderRadius: radii.control,
		backgroundColor: colors.primary,
		color: colors.bg,
		fontWeight: 750,
	},
	blockText: {
		display: "block",
	},
	mutedText: {
		color: colors.muted,
		fontSize: sizes.textSm,
	},
	controlBase: {
		display: "inline-flex",
		alignItems: "center",
		gap: space.four,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.surfaceRaised,
		color: colors.ink,
		cursor: "pointer",
		textDecoration: "none",
		transitionProperty: "border-color, background-color, color",
		transitionDuration: motion.fast,
		transitionTimingFunction: motion.ease,
		":focus-visible": {
			outline: "none",
			boxShadow: shadows.focus,
		},
	},
	interactiveHover: {
		":hover": {
			borderColor: colors.primary,
			backgroundColor: colors.primarySoft,
		},
	},
	stack: {
		display: "grid",
		gap: space.four,
	},
	calendarPanel: {
		display: "grid",
		gap: space.four,
		marginBottom: space.ten,
	},
	calendarHeader: {
		display: "grid",
		gridTemplateColumns: "auto minmax(0, 1fr) auto auto",
		alignItems: "center",
		gap: space.three,
		color: colors.ink,
		fontSize: sizes.textSm,
	},
	calendarTitle: {
		minWidth: 0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	calendarModeButton: {
		width: sizes.controlSm,
		height: sizes.controlSm,
		justifyContent: "center",
		padding: 0,
		fontSize: sizes.textSm,
		lineHeight: 1,
		whiteSpace: "nowrap",
	},
	weekdayGrid: {
		display: "grid",
		gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
		gap: space.one,
		color: colors.muted,
		fontSize: sizes.textXs,
		textAlign: "center",
	},
	calendarGrid: {
		display: "grid",
		gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
		gap: space.one,
	},
	calendarDay: {
		position: "relative",
		display: "grid",
		height: "28px",
		minWidth: 0,
		placeItems: "center",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: "transparent",
		borderRadius: radii.tag,
		backgroundColor: "transparent",
		color: colors.ink,
		cursor: "pointer",
		fontSize: sizes.textSm,
		lineHeight: 1,
		":hover": {
			borderColor: colors.border,
			backgroundColor: colors.surfaceRaised,
		},
		":focus-visible": {
			outline: "none",
			boxShadow: shadows.focus,
		},
	},
	calendarDayOutside: {
		color: colors.subtle,
	},
	calendarDaySelected: {
		borderColor: colors.primary,
		backgroundColor: colors.primarySoft,
		color: colors.primaryHover,
		fontWeight: 700,
	},
	calendarDayToday: {
		borderColor: colors.border,
	},
	calendarDot: {
		position: "absolute",
		bottom: "3px",
		width: "4px",
		height: "4px",
		borderRadius: "50%",
		backgroundColor: colors.primary,
	},
	sidebarSection: {
		display: "grid",
		gap: space.four,
		marginTop: space.ten,
	},
	sectionHeaderRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: space.four,
	},
	sectionHeading: {
		margin: 0,
		fontSize: sizes.textMd,
		fontWeight: 700,
	},
	emptyHint: {
		color: colors.muted,
		fontSize: sizes.textSm,
		lineHeight: 1.4,
	},
	miniAppRow: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) auto",
		gap: space.three,
	},
	miniAppPrimaryButton: {
		display: "grid",
		gridTemplateColumns: "auto minmax(0, 1fr)",
		justifyContent: "stretch",
		width: "100%",
		paddingTop: space.four,
		paddingRight: space.five,
		paddingBottom: space.four,
		paddingLeft: space.five,
		textAlign: "left",
		fontSize: sizes.textMd,
	},
	workspace: {
		display: "flex",
		flexDirection: "column",
		minHeight: "100vh",
		minWidth: 0,
		backgroundColor: colors.bg,
	},
	workspaceTabs: {
		display: "flex",
		gap: space.three,
		minWidth: 0,
		overflow: "auto",
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
		backgroundColor: colors.surface,
		paddingTop: space.four,
		paddingRight: space.twelve,
		paddingBottom: space.four,
		paddingLeft: space.twelve,
		"@media (max-width: 760px)": {
			paddingRight: space.nine,
			paddingLeft: space.nine,
		},
	},
	workspaceTabGroup: {
		display: "inline-flex",
		flexShrink: 0,
	},
	workspaceTab: {
		maxWidth: "240px",
		flexShrink: 0,
		paddingTop: space.three,
		paddingRight: space.four,
		paddingBottom: space.three,
		paddingLeft: space.four,
		overflow: "hidden",
		fontSize: sizes.textSm,
		whiteSpace: "nowrap",
	},
	workspaceTabJoined: {
		borderTopRightRadius: 0,
		borderBottomRightRadius: 0,
	},
	workspaceTabActive: {
		borderColor: colors.primary,
		backgroundColor: colors.primarySoft,
		color: colors.primaryHover,
	},
	workspaceTabClose: {
		width: sizes.controlSm,
		height: "100%",
		flexShrink: 0,
		justifyContent: "center",
		borderLeftWidth: "0",
		borderTopLeftRadius: 0,
		borderBottomLeftRadius: 0,
		padding: 0,
	},
	workspaceHeader: {
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "space-between",
		gap: space.eight,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
		paddingTop: space.ten,
		paddingRight: space.twelve,
		paddingBottom: space.nine,
		paddingLeft: space.twelve,
		"@media (max-width: 760px)": {
			display: "grid",
			paddingTop: space.nine,
			paddingRight: space.nine,
			paddingBottom: space.nine,
			paddingLeft: space.nine,
		},
	},
	pageTitle: {
		marginTop: space.three,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		fontSize: sizes.textXl,
		lineHeight: 1.15,
		letterSpacing: 0,
	},
	iconButton: {
		width: sizes.controlSm,
		height: sizes.controlSm,
		justifyContent: "center",
		padding: 0,
	},
	saveState: {
		display: "inline-flex",
		alignItems: "center",
		gap: space.four,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.pill,
		paddingTop: space.three,
		paddingRight: space.five,
		paddingBottom: space.three,
		paddingLeft: space.five,
		color: colors.muted,
		fontSize: sizes.textSm,
	},
	saveSaving: {
		color: colors.warning,
	},
	saveSaved: {
		color: colors.success,
	},
	saveError: {
		color: colors.danger,
	},
	editorToolbar: {
		display: "flex",
		flexWrap: "wrap",
		gap: space.four,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
		paddingTop: space.five,
		paddingRight: space.twelve,
		paddingBottom: space.five,
		paddingLeft: space.twelve,
		"@media (max-width: 760px)": {
			paddingRight: space.nine,
			paddingLeft: space.nine,
		},
	},
	toolbarButton: {
		paddingTop: space.three,
		paddingRight: space.five,
		paddingBottom: space.three,
		paddingLeft: space.five,
		fontSize: sizes.textMd,
	},
	editorPanel: {
		flex: 1,
		minWidth: 0,
		overflow: "auto",
		paddingTop: space.thirteen,
		paddingRight: space.twelve,
		paddingBottom: "60px",
		paddingLeft: space.twelve,
		"@media (max-width: 760px)": {
			paddingRight: space.nine,
			paddingLeft: space.nine,
		},
	},
	workspaceApp: {
		display: "flex",
		flex: 1,
		minHeight: 0,
		minWidth: 0,
		flexDirection: "column",
	},
	workspaceFrame: {
		flex: 1,
		width: "100%",
		minHeight: "520px",
		borderWidth: "0",
		backgroundColor: colors.bg,
	},
	slashMenu: {
		position: "fixed",
		zIndex: zIndex.modalBackdrop,
		width: "340px",
		overflow: "hidden",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.modal,
		backgroundColor: colors.bg,
		boxShadow: shadows.popover,
	},
	slashMenuHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: space.four,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
		paddingTop: space.four,
		paddingRight: space.five,
		paddingBottom: space.four,
		paddingLeft: space.five,
		color: colors.muted,
		fontSize: sizes.textSm,
	},
	slashItem: {
		display: "grid",
		gridTemplateColumns: "auto minmax(0, 1fr) auto",
		alignItems: "center",
		width: "100%",
		gap: space.four,
		borderWidth: "0",
		backgroundColor: "transparent",
		padding: space.five,
		color: colors.ink,
		textAlign: "left",
		cursor: "pointer",
	},
	slashItemActive: {
		backgroundColor: colors.primarySoft,
		color: colors.primaryHover,
	},
	slashIcon: {
		display: "grid",
		width: sizes.controlSm,
		height: sizes.controlSm,
		placeItems: "center",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.surface,
	},
	slashEmpty: {
		padding: space.six,
		color: colors.muted,
		fontSize: sizes.textSm,
	},
	extensionBlock: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) auto",
		alignItems: "center",
		gap: space.six,
		marginTop: space.six,
		marginBottom: space.six,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.panel,
		backgroundColor: colors.surface,
		padding: space.seven,
		color: colors.ink,
		fontSize: sizes.textMd,
		lineHeight: 1.4,
		"@media (max-width: 760px)": {
			gridTemplateColumns: "1fr",
		},
	},
	extensionBlockError: {
		borderColor: colors.dangerBorder,
		backgroundColor: colors.dangerSoft,
	},
	extensionBlockDraft: {
		gridTemplateColumns: "1fr",
		borderColor: colors.primary,
		backgroundColor: colors.surfaceRaised,
	},
	extensionBlockBody: {
		display: "grid",
		minWidth: 0,
		gap: space.two,
	},
	extensionBlockHeader: {
		display: "flex",
		flexWrap: "wrap",
		alignItems: "center",
		gap: space.three,
		color: colors.muted,
		fontSize: sizes.textXs,
	},
	extensionBlockKind: {
		fontFamily: fonts.mono,
	},
	extensionBlockStatus: {
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.pill,
		paddingTop: space.one,
		paddingRight: space.three,
		paddingBottom: space.one,
		paddingLeft: space.three,
		textTransform: "capitalize",
	},
	extensionBlockTitle: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: sizes.textBase,
	},
	extensionBlockPrompt: {
		color: colors.primaryHover,
		fontSize: sizes.textSm,
	},
	extensionBlockSummary: {
		display: "-webkit-box",
		overflow: "hidden",
		color: colors.muted,
		fontSize: sizes.textSm,
		WebkitBoxOrient: "vertical",
		WebkitLineClamp: 3,
	},
	extensionBlockActions: {
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "flex-end",
		gap: space.three,
	},
	agentRequestForm: {
		display: "grid",
		gap: space.five,
		minWidth: 0,
	},
	agentContext: {
		display: "grid",
		gap: space.two,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.surface,
		padding: space.four,
	},
	agentContextPrompt: {
		overflow: "hidden",
		color: colors.primaryHover,
		fontSize: sizes.textSm,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	agentRequestField: {
		display: "grid",
		gap: space.two,
		minWidth: 0,
	},
	agentRequestLabelRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: space.four,
		minWidth: 0,
	},
	promptRefineButton: {
		flexShrink: 0,
		paddingTop: space.two,
		paddingRight: space.four,
		paddingBottom: space.two,
		paddingLeft: space.four,
		color: colors.primaryHover,
		fontSize: sizes.textSm,
		":disabled": {
			cursor: "not-allowed",
			opacity: 0.55,
		},
	},
	promptRefineGlyph: {
		fontSize: sizes.textMd,
		lineHeight: 1,
	},
	agentRequestPrompt: {
		minHeight: "92px",
		resize: "vertical",
		lineHeight: 1.45,
	},
	agentRequestError: {
		color: colors.danger,
		fontSize: sizes.textSm,
		lineHeight: 1.35,
	},
	agentRequestActions: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) auto",
		alignItems: "center",
		gap: space.five,
		"@media (max-width: 760px)": {
			gridTemplateColumns: "1fr",
			justifyItems: "start",
		},
	},
	agentRequestButtons: {
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "flex-end",
		gap: space.three,
	},
	floatingAgentTray: {
		position: "fixed",
		right: space.nine,
		bottom: space.nine,
		zIndex: "40",
		display: "grid",
		width: "min(460px, calc(100vw - 32px))",
		gap: space.four,
		pointerEvents: "none",
		"@media (max-width: 760px)": {
			right: space.six,
			bottom: space.six,
			width: "calc(100vw - 24px)",
		},
	},
	floatingAgentTile: {
		display: "grid",
		gap: space.four,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.panel,
		backgroundColor: colors.surfaceRaised,
		boxShadow: shadows.popover,
		padding: space.six,
		pointerEvents: "auto",
		color: colors.ink,
		fontSize: sizes.textMd,
		lineHeight: 1.4,
	},
	floatingAgentTileError: {
		borderColor: colors.dangerBorder,
		backgroundColor: colors.dangerSoft,
	},
	floatingAgentHeader: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) auto",
		alignItems: "start",
		gap: space.four,
	},
	floatingAgentStream: {
		display: "grid",
		gap: space.one,
		maxHeight: "132px",
		overflow: "auto",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.surface,
		padding: space.four,
		color: colors.muted,
		fontFamily: fonts.mono,
		fontSize: sizes.textXs,
		lineHeight: 1.45,
		overflowWrap: "anywhere",
	},
	floatingAgentActions: {
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "flex-end",
		gap: space.three,
	},
	panel: {
		display: "grid",
		gap: space.six,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.panel,
		backgroundColor: colors.surfaceRaised,
		padding: space.seven,
		marginBottom: space.six,
	},
	panelHeading: {
		display: "flex",
		alignItems: "center",
		gap: space.four,
	},
	field: {
		width: "100%",
		minWidth: 0,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.bg,
		paddingTop: space.four,
		paddingRight: space.five,
		paddingBottom: space.four,
		paddingLeft: space.five,
		color: colors.ink,
		"::placeholder": {
			color: colors.muted,
		},
		":focus": {
			outline: "none",
			boxShadow: shadows.focus,
		},
	},
	resourceRow: {
		display: "grid",
		gap: space.one,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		padding: space.four,
		color: colors.ink,
		textDecoration: "none",
		":focus-visible": {
			outline: "none",
			boxShadow: shadows.focus,
		},
	},
	rowMeta: {
		color: colors.muted,
		fontSize: sizes.textSm,
	},
	auditRow: {
		gap: space.two,
	},
	auditList: {
		display: "grid",
		gap: space.four,
		maxHeight: "min(64vh, 620px)",
		overflow: "auto",
		padding: space.four,
	},
	auditHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: space.four,
		minWidth: 0,
	},
	auditTitle: {
		minWidth: 0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	auditStatus: {
		flexShrink: 0,
		maxWidth: "58%",
		overflow: "hidden",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.pill,
		paddingTop: space.one,
		paddingRight: space.four,
		paddingBottom: space.one,
		paddingLeft: space.four,
		color: colors.muted,
		fontSize: sizes.textXs,
		lineHeight: 1.45,
		textOverflow: "ellipsis",
		textTransform: "capitalize",
		whiteSpace: "nowrap",
	},
	auditStatusSuccess: {
		borderColor: colors.successBorder,
		backgroundColor: colors.successSoft,
		color: colors.success,
	},
	auditStatusWarning: {
		borderColor: colors.warningBorder,
		backgroundColor: colors.warningSoft,
		color: colors.warningText,
	},
	auditStatusDanger: {
		borderColor: colors.dangerBorder,
		backgroundColor: colors.dangerSoft,
		color: colors.danger,
	},
	auditSummary: {
		display: "-webkit-box",
		overflow: "hidden",
		color: colors.ink,
		fontSize: sizes.textSm,
		lineHeight: 1.35,
		WebkitBoxOrient: "vertical",
		WebkitLineClamp: 2,
	},
	inlineForm: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) minmax(0, 0.8fr) auto",
		gap: space.three,
	},
	inlineFormSingle: {
		gridTemplateColumns: "minmax(0, 1fr) auto",
	},
	primaryIconButton: {
		width: sizes.controlLg,
		justifyContent: "center",
		padding: 0,
		backgroundColor: colors.primary,
		color: colors.bg,
		":hover": {
			backgroundColor: colors.primaryHover,
		},
	},
	primaryTextButton: {
		justifyContent: "center",
		paddingTop: space.three,
		paddingRight: space.five,
		paddingBottom: space.three,
		paddingLeft: space.five,
		backgroundColor: colors.primary,
		color: colors.bg,
		fontSize: sizes.textMd,
		":hover": {
			backgroundColor: colors.primaryHover,
		},
		":disabled": {
			cursor: "wait",
			opacity: 0.72,
		},
	},
	kanbanPreview: {
		display: "grid",
		gap: space.five,
	},
	kanbanColumns: {
		display: "grid",
		gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
		gap: space.four,
		"@media (max-width: 760px)": {
			gridTemplateColumns: "1fr",
		},
	},
	kanbanColumn: {
		minWidth: 0,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.surface,
		padding: space.four,
	},
	kanbanColumnTitle: {
		display: "block",
		marginBottom: space.three,
		fontSize: sizes.textSm,
	},
	kanbanCard: {
		display: "block",
		overflow: "hidden",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.tag,
		backgroundColor: colors.bg,
		padding: space.three,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: sizes.textSm,
	},
	paletteBackdrop: {
		position: "fixed",
		inset: 0,
		zIndex: zIndex.modalBackdrop,
		display: "grid",
		alignItems: "start",
		justifyItems: "center",
		backgroundColor: colors.backdrop,
		paddingTop: "12vh",
		paddingRight: space.eight,
		paddingBottom: space.eight,
		paddingLeft: space.eight,
	},
	palette: {
		width: "min(680px, 100%)",
		overflow: "hidden",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.modal,
		backgroundColor: colors.bg,
		boxShadow: shadows.popover,
	},
	workflowDialog: {
		width: "min(860px, 100%)",
	},
	paletteInput: {
		display: "flex",
		alignItems: "center",
		gap: space.five,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
		padding: space.six,
	},
	paletteField: {
		borderWidth: "0",
		paddingTop: space.two,
		paddingRight: 0,
		paddingBottom: space.two,
		paddingLeft: 0,
	},
	paletteList: {
		display: "grid",
		maxHeight: "420px",
		overflow: "auto",
		padding: space.four,
	},
	paletteButton: {
		display: "grid",
		gridTemplateColumns: "auto minmax(0, 1fr) auto",
		width: "100%",
		borderColor: "transparent",
		padding: space.five,
		textAlign: "left",
	},
	paletteButtonActive: {
		borderColor: colors.primary,
		backgroundColor: colors.primarySoft,
		color: colors.primaryHover,
	},
	paletteLabel: {
		display: "grid",
		gap: space.one,
	},
	paletteMeta: {
		display: "block",
		color: colors.muted,
		fontSize: sizes.textSm,
		fontStyle: "normal",
	},
	pinList: {
		display: "grid",
		maxHeight: "420px",
		overflow: "auto",
		padding: space.four,
	},
	pinRow: {
		display: "grid",
		gridTemplateColumns: "auto minmax(0, 1fr)",
		alignItems: "start",
		gap: space.five,
		borderRadius: radii.control,
		padding: space.five,
		cursor: "pointer",
		":hover": {
			backgroundColor: colors.surface,
		},
	},
	workflowList: {
		display: "grid",
		gap: space.four,
		maxHeight: "min(64vh, 620px)",
		overflow: "auto",
		padding: space.four,
	},
	workflowEmpty: {
		display: "grid",
		gap: space.two,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.surface,
		padding: space.six,
		color: colors.muted,
	},
	workflowRow: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) auto",
		alignItems: "start",
		gap: space.six,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.surfaceRaised,
		padding: space.six,
		"@media (max-width: 760px)": {
			gridTemplateColumns: "1fr",
		},
	},
	workflowMain: {
		display: "grid",
		gap: space.five,
		minWidth: 0,
	},
	workflowTitleRow: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) auto",
		alignItems: "start",
		gap: space.four,
	},
	workflowMetaGrid: {
		display: "grid",
		gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
		gap: space.four,
		"@media (max-width: 760px)": {
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
		},
	},
	workflowMetaItem: {
		display: "grid",
		gap: space.one,
		minWidth: 0,
	},
	workflowMetaLabel: {
		color: colors.muted,
		fontSize: sizes.textXs,
	},
	workflowMetaValue: {
		overflow: "hidden",
		color: colors.ink,
		fontSize: sizes.textSm,
		lineHeight: 1.4,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	workflowToggle: {
		display: "flex",
		alignItems: "center",
		gap: space.three,
		minHeight: sizes.controlMd,
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.bg,
		paddingTop: space.three,
		paddingRight: space.four,
		paddingBottom: space.three,
		paddingLeft: space.four,
		color: colors.ink,
		fontSize: sizes.textMd,
		cursor: "pointer",
	},
	workflowCheckbox: {
		width: "16px",
		height: "16px",
		accentColor: colors.primary,
	},
	workflowError: {
		margin: 0,
		color: colors.danger,
		fontSize: sizes.textSm,
		lineHeight: 1.4,
	},
	bindingChipList: {
		display: "flex",
		flexWrap: "wrap",
		gap: space.three,
	},
	bindingChip: {
		display: "grid",
		gap: space.one,
		minWidth: "160px",
		maxWidth: "280px",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: colors.border,
		borderRadius: radii.control,
		backgroundColor: colors.bg,
		paddingTop: space.three,
		paddingRight: space.four,
		paddingBottom: space.three,
		paddingLeft: space.four,
		color: colors.ink,
		fontSize: sizes.textSm,
		lineHeight: 1.3,
		overflowWrap: "anywhere",
	},
	documentPanel: {
		position: "sticky",
		top: 0,
		gridColumn: "3",
		display: "grid",
		gridTemplateRows: "auto minmax(0, 1fr)",
		height: "100vh",
		borderLeftWidth: "1px",
		borderLeftStyle: "solid",
		borderLeftColor: colors.border,
		backgroundColor: colors.bg,
		boxShadow: shadows.popover,
		"@media (max-width: 1180px)": {
			position: "relative",
			top: "auto",
			gridColumn: "2",
			height: "min(72vh, 760px)",
			borderTopWidth: "1px",
			borderTopStyle: "solid",
			borderTopColor: colors.border,
		},
		"@media (max-width: 760px)": {
			gridColumn: "1",
			height: "min(72vh, 680px)",
			borderLeftWidth: "0",
		},
	},
	documentPanelHeader: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) auto",
		alignItems: "center",
		gap: space.four,
		borderBottomWidth: "1px",
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
		padding: space.four,
	},
	documentTabs: {
		display: "flex",
		minWidth: 0,
		overflow: "auto",
		gap: space.three,
	},
	documentTab: {
		flexShrink: 0,
		maxWidth: "220px",
		paddingTop: space.three,
		paddingRight: space.four,
		paddingBottom: space.three,
		paddingLeft: space.four,
	},
	documentTabActive: {
		borderColor: colors.primary,
		backgroundColor: colors.primarySoft,
		color: colors.primaryHover,
	},
	documentFrame: {
		width: "100%",
		height: "100%",
		borderWidth: "0",
		backgroundColor: colors.bg,
	},
	agentPanel: {
		display: "grid",
		gap: space.four,
	},
	agentTranscript: {
		display: "grid",
		gap: space.three,
		maxHeight: "240px",
		overflow: "auto",
		paddingRight: space.one,
	},
	agentEmpty: {
		display: "inline-flex",
		alignItems: "center",
		gap: space.three,
		color: colors.muted,
		fontSize: sizes.textSm,
	},
	agentMessage: {
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
		borderLeftWidth: "2px",
		borderLeftStyle: "solid",
		borderLeftColor: colors.border,
		paddingTop: space.two,
		paddingRight: 0,
		paddingBottom: space.two,
		paddingLeft: space.four,
		color: colors.ink,
		fontSize: sizes.textSm,
		lineHeight: 1.45,
	},
	agentUserMessage: {
		borderLeftColor: colors.primary,
		color: colors.primaryHover,
	},
	agentSystemMessage: {
		borderLeftColor: colors.danger,
		color: colors.danger,
	},
	agentTextArea: {
		minHeight: "84px",
		resize: "vertical",
		lineHeight: 1.4,
	},
	agentActions: {
		display: "grid",
		gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
		gap: space.three,
	},
	agentLink: {
		color: colors.primary,
		fontWeight: 650,
		textDecoration: "none",
		":focus-visible": {
			outline: "none",
			boxShadow: shadows.focus,
		},
	},
	inlineCode: {
		fontFamily: fonts.mono,
		fontSize: sizes.textXs,
	},
});
