// SupertagModuleGenerator.swift
// EnchiridionImporter
//
// Plan P1 "Pre-migration step: enumerate the old vault's runtime
// user-created supertags and generate a TS module from each definition
// (mechanical: the definitions are JSON)." Generates ONE `defineSupertagModule(...)`
// TS source file per `OldSupertagDefinition` that
// `OldSupertagOwnershipResolver.isRuntimeUserCreated` accepts, matching the
// shape `packages/schema/src/registry.ts`'s `defineSupertagModule` /
// `types.ts`'s `SupertagModule` expect and the hand-authored style
// `supertags/core/src/index.ts` already establishes (`f.text()`/
// `f.select([...])`/... field builders, a `MODULE_ID` constant, a default
// export).
//
// SCOPE (this is intentionally a MECHANICAL translation, not a semantic
// migration — the generated files are meant to be reviewed before loading,
// per the task brief "so they can be reviewed and loaded like any other
// supertag module"):
//   - Field types map 1:1 onto `packages/schema`'s `f.*` builders.
//   - `entityReference` `allowedSupertagIDs` and a supertag's `parentIDs`
//     are emitted as the OLD app's bare/raw ids (e.g. `"person"`, or
//     `"tag-3f9a..."` for another runtime tag) — NOT resolved to the
//     migrated modules' real qualified ids (e.g.
//     `dev.rawkode.enchiridion.core.person`). Resolving that safely needs
//     the full old-vault supertag catalog cross-referenced against
//     `supertags/core`'s `CoreSupertagIDs` (and any sibling generated
//     modules, for a user tag that references another user tag) — real,
//     bounded follow-up work, explicitly flagged both here and in the
//     generated file itself with a `// TODO(review)` comment, rather than
//     guessed at.
import Foundation

public enum SupertagModuleGenerator {
  /// Derives a filesystem/TS-identifier-safe slug from an old runtime
  /// supertag id (typically `"tag-<uuid>"`, `SupertagID.random()`) —
  /// lowercase, non-alphanumeric runs collapsed to a single hyphen, no
  /// leading/trailing hyphen. Used as both the generated module's object
  /// key (`supertags: { <slug>: {...} }`) and its output filename.
  public static func slug(forOldSupertagID id: String) -> String {
    let lowered = id.lowercased()
    var slug = ""
    var lastWasSeparator = false
    for scalar in lowered.unicodeScalars {
      if CharacterSet.alphanumerics.contains(scalar) {
        slug.unicodeScalars.append(scalar)
        lastWasSeparator = false
      } else if !lastWasSeparator {
        slug.append("-")
        lastWasSeparator = true
      }
    }
    while slug.hasPrefix("-") { slug.removeFirst() }
    while slug.hasSuffix("-") { slug.removeLast() }
    return slug.isEmpty ? "imported" : slug
  }

  public static func moduleID(forSlug slug: String) -> String {
    "dev.rawkode.imported.\(slug)"
  }

  /// Generates the full TS source for one supertag module.
  public static func generateModule(from definition: OldSupertagDefinition) -> String {
    let slug = slug(forOldSupertagID: definition.id)
    let moduleID = moduleID(forSlug: slug)

    let liveFields = definition.fields.filter { !$0.isDeleted }
    let fieldsSource =
      liveFields
      .map { "    " + fieldSource(for: $0) }
      .joined(separator: "\n")

    let parentsLine: String
    if definition.parentIDs.isEmpty {
      parentsLine = ""
    } else {
      let list = definition.parentIDs.map(tsStringLiteral).joined(separator: ", ")
      parentsLine = "\n    parents: [\(list)], // TODO(review): old app ids — see file header\n"
    }

    return """
      // AUTO-GENERATED by EnchiridionImporter (packages/schema's
      // `defineSupertagModule` contract) from the old app's runtime
      // supertag "\(definition.id)" ("\(definition.name)"). Plan §Phasing P1:
      // "Pre-migration step: enumerate the old vault's runtime
      // user-created supertags and generate a TS module from each
      // definition." Review before loading — this is a mechanical
      // translation of stored JSON, not a hand-authored module. See the
      // `// TODO(review)` markers below for what specifically needs a human
      // decision before this ships.

      import { defineSupertagModule, f, type SupertagModule } from "@enchiridion/schema";

      const MODULE_ID = "\(moduleID)";

      const supertags: SupertagModule["supertags"] = {
        \(slug): {
          name: \(tsStringLiteral(definition.name)),
          symbol: \(tsStringLiteral(definition.symbol)),\(parentsLine)
          fields: {
      \(fieldsSource)
          },
        },
      };

      export default defineSupertagModule({
        id: MODULE_ID,
        version: 1,
        supertags,
      });
      """
  }

  private static func fieldSource(for field: OldSupertagFieldDefinition) -> String {
    let key = tsPropertyKey(field.id)
    switch field.type {
    case "text": return "\(key): f.text(\(commonOptions(field))),"
    case "number": return "\(key): f.number(\(commonOptions(field))),"
    case "boolean": return "\(key): f.boolean(\(commonOptions(field))),"
    case "date": return "\(key): f.date(\(commonOptions(field))),"
    case "dateTime": return "\(key): f.dateTime(\(commonOptions(field))),"
    case "url": return "\(key): f.url(\(commonOptions(field))),"
    case "email": return "\(key): f.email(\(commonOptions(field))),"
    case "phone": return "\(key): f.phone(\(commonOptions(field))),"
    case "select":
      let options = field.options.map { tsStringLiteral($0.name) }.joined(separator: ", ")
      return "\(key): f.select([\(options)], \(commonOptions(field, includeMultiline: false))),"
    case "entityReference":
      let allowed = field.allowedSupertagIDs.map(tsStringLiteral).joined(separator: ", ")
      return
        "\(key): f.entityReference([\(allowed)], \(commonOptions(field, includeMultiline: false))), // TODO(review): allowedSupertagIDs are old app ids — see file header"
    default:
      return
        "\(key): f.text(\(commonOptions(field))), // TODO(review): unrecognized old field type \"\(field.type)\", defaulted to text"
    }
  }

  private static func commonOptions(_ field: OldSupertagFieldDefinition, includeMultiline: Bool = true) -> String {
    var parts: [String] = ["name: \(tsStringLiteral(field.name))"]
    if includeMultiline && field.isMultiline { parts.append("isMultiline: true") }
    if field.allowsMultiple { parts.append("allowsMultiple: true") }
    if field.isRequired { parts.append("isRequired: true") }
    return "{ \(parts.joined(separator: ", ")) }"
  }

  private static func tsPropertyKey(_ id: String) -> String {
    // A safe TS object-key identifier check: letters/digits/underscore
    // only, not starting with a digit. Old field ids are typically already
    // hyphenated slugs (e.g. "estimated-minutes") which are NOT valid bare
    // identifiers, so those (and anything else non-conforming) are quoted
    // string keys instead — both are valid `Record<string, ...>` keys, and
    // `supertags/core/src/index.ts` already uses quoted hyphenated keys
    // for exactly this reason (e.g. `"relationship-notes"`).
    let isSimpleIdentifier =
      !id.isEmpty
      && id.allSatisfy { $0.isLetter || $0.isNumber || $0 == "_" }
      && !(id.first?.isNumber ?? false)
    return isSimpleIdentifier ? id : tsStringLiteral(id)
  }

  private static func tsStringLiteral(_ value: String) -> String {
    var escaped = ""
    escaped.reserveCapacity(value.count + 2)
    for character in value {
      switch character {
      case "\\": escaped += "\\\\"
      case "\"": escaped += "\\\""
      case "\n": escaped += "\\n"
      default: escaped.append(character)
      }
    }
    return "\"\(escaped)\""
  }
}
