[package]
name = "multipass-hardware"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"

[target.'cfg(target_os = "macos")'.dependencies]
hidapi = { version = "2.6.7", default-features = false, features = ["macos-shared-device"] }

[target.'cfg(target_os = "linux")'.dependencies]
hidapi = { version = "2.6.7", default-features = false, features = ["linux-native-basic-udev"] }

[target.'cfg(target_os = "windows")'.dependencies]
hidapi = { version = "2.6.7", default-features = false, features = ["windows-native"] }
