style = "compact"

# This stops the terminal from clearing the screen when you exit Atuin
inline_height = 0

enter_accept = true
show_preview = true

search_mode = "skim"

filter_mode = "directory"
filter_mode_shell_up_key_binding = "session"
