name = "web-links"
compatibility_date = "2022-01-20"
workers_dev = true
routes = [
  { pattern = "rawkode.academy", custom_domain = true },
  { pattern = "rawkode.community", custom_domain = true },
  { pattern = "rawkode.link", custom_domain = true }
]
