apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: awesome-o
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/rawkode/rawkode
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: awesome-o
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./opt/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: awesome-o
  validation: client
