import type { ExtensionManifest, ScheduledWorkflow } from "./types";

export const builtinExtensionManifests: ExtensionManifest[] = [
	{
		slug: "bookmarks",
		name: "Bookmarks",
		version: "0.1.0",
		description: "Capture, search, and embed bookmark collections inside daily notes.",
		status: "builtin",
		routes: [
			{ path: "/apps/bookmarks", mode: "host-primitive", label: "Bookmarks" },
			{ path: "/apps/bookmarks/fragment", mode: "worker-fragment", label: "Bookmark query fragment" },
		],
		commands: [
			{
				id: "create-bookmark",
				label: "Create bookmark",
				description: "Save a URL with title, notes, and tags.",
				kind: "create",
				scope: "global",
				app: "bookmarks",
				action: "bookmarks.create",
				requiredHostApis: ["bookmarks:write", "resource-index:write"],
			},
			{
				id: "open-bookmarks",
				label: "Open bookmarks",
				description: "Open the bookmarks app page.",
				kind: "navigate",
				scope: "global",
				app: "bookmarks",
				action: "/apps/bookmarks",
				requiredHostApis: ["bookmarks:read"],
			},
			{
				id: "insert-bookmark-query",
				label: "Insert bookmark query",
				description: "Embed a live bookmark query in the current note.",
				kind: "insert-block",
				scope: "daily-note",
				app: "bookmarks",
				action: "bookmark-query",
				requiredHostApis: ["bookmarks:read"],
			},
		],
		editorBlocks: [
			{
				id: "bookmark-query",
				app: "bookmarks",
				label: "Bookmark query",
				description: "Shows bookmarks that match an optional tag.",
				defaultProps: { tag: "", sort: "newest" },
				renderer: "host-primitive",
				requiredHostApis: ["bookmarks:read"],
			},
		],
		workflows: [],
		bindings: [
			{ type: "kv_namespace", name: "BOOKMARKS_KV", purpose: "Optional isolated cache for generated bookmark variants." },
		],
		hostApis: ["bookmarks:read", "bookmarks:write", "resource-index:write"],
		indexProjections: [
			{ sourceType: "bookmark", titlePath: "title", summaryPath: "description", urlPath: "url", tagsPath: "tags" },
		],
	},
	{
		slug: "projects",
		name: "Projects",
		version: "0.1.0",
		description: "Track projects and Kanban boards, then embed board views in notes.",
		status: "builtin",
		routes: [
			{ path: "/apps/projects", mode: "host-primitive", label: "Projects" },
			{ path: "/apps/projects/fragment", mode: "worker-fragment", label: "Project board fragment" },
		],
		commands: [
			{
				id: "create-project",
				label: "Create project",
				description: "Create a project with a default Kanban board.",
				kind: "create",
				scope: "global",
				app: "projects",
				action: "projects.create",
				requiredHostApis: ["projects:write", "resource-index:write"],
			},
			{
				id: "create-card",
				label: "Create Kanban card",
				description: "Add a card to the active project board.",
				kind: "create",
				scope: "global",
				app: "projects",
				action: "cards.create",
				requiredHostApis: ["projects:write"],
			},
			{
				id: "insert-kanban-board",
				label: "Insert Kanban board",
				description: "Embed a trusted host-rendered Kanban board.",
				kind: "insert-block",
				scope: "daily-note",
				app: "projects",
				action: "kanban-board",
				requiredHostApis: ["projects:read"],
			},
		],
		editorBlocks: [
			{
				id: "kanban-board",
				app: "projects",
				label: "Kanban board",
				description: "Shows a board with columns and cards.",
				defaultProps: { boardId: "default" },
				renderer: "host-primitive",
				requiredHostApis: ["projects:read"],
			},
		],
		workflows: [],
		bindings: [
			{ type: "d1_database", name: "PROJECTS_DB", purpose: "Optional isolated project app state for promoted variants." },
		],
		hostApis: ["projects:read", "projects:write", "resource-index:write"],
		indexProjections: [
			{ sourceType: "project", titlePath: "name", summaryPath: "description" },
			{ sourceType: "kanban-card", titlePath: "title", summaryPath: "description" },
		],
	},
];

export const builtinScheduledWorkflows: ScheduledWorkflow[] = [
	{
		id: "morning-brief",
		extensionSlug: null,
		name: "Morning brief",
		cron: "0 7 * * *",
		workflowName: "daily-brief",
		payload: { include: ["calendar", "gmail", "github", "open-loops"] },
		enabled: false,
		lastRunAt: null,
		createdAt: "2026-06-17T00:00:00.000Z",
		updatedAt: "2026-06-17T00:00:00.000Z",
	},
	{
		id: "weekly-open-loop-review",
		extensionSlug: null,
		name: "Weekly open-loop review",
		cron: "0 17 * * 5",
		workflowName: "open-loop-review",
		payload: { horizonDays: 14 },
		enabled: false,
		lastRunAt: null,
		createdAt: "2026-06-17T00:00:00.000Z",
		updatedAt: "2026-06-17T00:00:00.000Z",
	},
];
