---
image: quay.io/buildah/stable

stages:
  - build

variables:
  MY_IMAGE_NAME: "rawkos"
  MY_IMAGE_DESC: "rawkOS"
  IMAGE_REGISTRY: "$CI_REGISTRY_IMAGE"
  REGISTRY_USER: "$CI_REGISTRY_USER"
  REGISTRY_PASSWORD: "$CI_REGISTRY_PASSWORD"

build:
  before_script:
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  stage: build
  script:
    - export TIMESTAMP="$(date +%Y%m%d)"
    - export SHA_SHORT="$(echo $CI_COMMIT_SHA | cut -c1-7)"
    - |
      echo CI Variables - TIMESTAMP: $TIMESTAMP, SHA_SHORT: $SHA_SHORT
    - |
      echo "Determining alias tags..."
      if [ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]; then
        # For merge requests, tags are like "pr-123 abcdef0"
        CURRENT_ALIAS_TAGS="pr-$CI_MERGE_REQUEST_IID $SHA_SHORT"
      else
        # For main branch, schedules, web, tags are like "20230101 latest"
        CURRENT_ALIAS_TAGS="$TIMESTAMP latest"
      fi
      echo "Determined alias tags: $CURRENT_ALIAS_TAGS"
      # Export for availability in subsequent multi-line script blocks
      export FINAL_ALIAS_TAGS="$CURRENT_ALIAS_TAGS"

    - |
      echo "Building image with tags: $FINAL_ALIAS_TAGS (Registry: $CI_REGISTRY_IMAGE, Image Name: $MY_IMAGE_NAME)"
      BUILD_TAG_ARGS=""
      # Loop over the space-separated tags in FINAL_ALIAS_TAGS
      for t in $FINAL_ALIAS_TAGS; do
        BUILD_TAG_ARGS="$BUILD_TAG_ARGS --tag $CI_REGISTRY_IMAGE/$MY_IMAGE_NAME:$t"
      done
      echo "Final buildah tag arguments: $BUILD_TAG_ARGS"

      buildah bud --file ./silverblue/Containerfile $BUILD_TAG_ARGS \
        --label "io.artifacthub.package.readme-url=$CI_PROJECT_URL/-/blob/main/README.md" \
        --label "org.opencontainers.image.description=$MY_IMAGE_DESC" \
        --label "org.opencontainers.image.title=$MY_IMAGE_NAME" \
        ./silverblue

    - |
      echo "Pushing image with tags: $FINAL_ALIAS_TAGS (Registry: $CI_REGISTRY_IMAGE, Image Name: $MY_IMAGE_NAME)"
      PUSH_IMAGE_ARGS=""
      # Loop over the space-separated tags in FINAL_ALIAS_TAGS
      for t in $FINAL_ALIAS_TAGS; do
        PUSH_IMAGE_ARGS="$PUSH_IMAGE_ARGS $CI_REGISTRY_IMAGE/$MY_IMAGE_NAME:$t"
      done
      echo "Final buildah push arguments: $PUSH_IMAGE_ARGS"

      buildah push $PUSH_IMAGE_ARGS
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "silverblue/**"
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - "silverblue/**"
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
