export MCFLY_LIGHT=FALSE
export MCFLY_RESULTS_SORT=LAST_RUN
export MCFLY_FUZZY=2
export MCFLY_RESULTS=10
export MCFLY_DISABLE_MENU=TRUE
export MCFLY_RESULTS_FILTER=CURRENT_DIRECTORY

eval "$(mcfly init zsh)"
