import { describe, expect, it } from "vitest"
import { LoroDoc, LoroList } from "loro-crdt"
import checkedInCorpus from "./fixtures/loro-prosemirror-v1-corpus.json"
import {
  applyDocumentThroughLoroSyncPlugin,
  buildLoroProseMirrorV1Corpus
} from "./loro-prosemirror-v1-corpus.js"
import { richTextSchemaAdapter } from "./rich-text/schema.js"

const sha256 = async (encoded: string): Promise<string> => {
  const binary = atob(encoded)
  const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0))
  const digest = await crypto.subtle.digest("SHA-256", bytes)
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("")
}

describe("Loro ProseMirror v1 compatibility corpus", () => {
  it("initializes and applies the official sync plugin before snapshotting", () => {
    const doc = new LoroDoc()
    doc.setPeerId("424242")
    const root = doc.getMap("corpus-plugin-regression")
    const target = richTextSchemaAdapter.schema.nodes.doc.create(null, [
      richTextSchemaAdapter.schema.nodes.paragraph.create(null, [
        richTextSchemaAdapter.schema.text("plugin transaction")
      ])
    ])

    const applied = applyDocumentThroughLoroSyncPlugin(doc, root, target)

    expect(applied.doc.eq(target)).toBe(true)
    expect(root.get("nodeName")).toBe("doc")
    expect(root.get("children")).toBeInstanceOf(LoroList)
  })

  it("is reproducibly generated by the production web schema and official plugin", async () => {
    const generated = buildLoroProseMirrorV1Corpus()
    expect(generated).toEqual({
      ...checkedInCorpus,
      fixtures: checkedInCorpus.fixtures.map(({ snapshotSHA256: _hash, ...fixture }) => fixture)
    })
    for (const fixture of checkedInCorpus.fixtures) {
      expect(await sha256(fixture.snapshotBase64), fixture.id).toBe(fixture.snapshotSHA256)
    }
  })
})
