// @enchiridion/supertags-imported
//
// Plan §Phasing P1: "Pre-migration step: enumerate the old vault's runtime
// user-created supertags and generate a TS module from each definition."
//
// Destination package for TS modules generated by
// `apps/swift/Sources/EnchiridionImporter/SupertagModuleGenerator.swift`
// from a real old-app vault's runtime user-created `SupertagDefinition`s —
// see that Swift file's header and `apps/swift/Sources/EnchiridionImporter/README.md`
// for the full generator contract and how to actually run it.
//
// Workflow:
//   1. `swift run EnchiridionImporter --old-vault-db <path> --supertags-out
//      projects/enchiridion/supertags/imported/src` writes one `<slug>.ts`
//      file per runtime user-created supertag found in the old vault, each
//      a `defineSupertagModule({...})` default export following
//      `supertags/core/src/index.ts`'s established shape.
//   2. REVIEW every generated file before wiring it in below — each one is
//      a MECHANICAL translation of stored JSON (field types/options), not
//      hand-authored, and carries `// TODO(review)` comments wherever the
//      generator couldn't safely resolve `entityReference`/`parents` ids to
//      the migrated modules' real qualified ids (e.g. the old bare
//      `"person"` needs to become `dev.rawkode.enchiridion.core.person` —
//      see `SupertagModuleGenerator.swift`'s header for why that resolution
//      isn't done automatically).
//   3. Re-export each reviewed module below and add it to `importedModules`
//      so anything loading `supertags/*` as a set picks it up.
//
// No generated modules are committed here yet — this task built and
// exercised the GENERATOR itself against small synthetic fixtures (see
// `apps/swift/Tests/EnchiridionImporterTests/SupertagModuleGeneratorTests.swift`),
// not a real migration run against anyone's actual vault. This file is the
// real, loadable (if currently empty) aggregation point that run will
// populate.
import type { SupertagModule } from "@enchiridion/schema";

/** Every reviewed, migrated supertag module. Add one entry per file wired
 *  in per step 3 above — e.g. `import sourdoughBake from "./sourdough-bake";`
 *  then `sourdoughBake` in this array. */
export const importedModules: readonly SupertagModule[] = [];

export default importedModules;
