[[ -f ${HOME}/Code/src/github.com/marlonrichert/zsh-snap/znap.zsh ]] ||
    (mkdir -p ${HOME}/Code/src/github.com/marlonrichert/zsh-snap && \
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git ${HOME}/Code/src/github.com/marlonrichert/zsh-snap)

source ${HOME}/Code/src/github.com/marlonrichert/zsh-snap/znap.zsh

znap eval iterm2 'curl -fsSL https://iterm2.com/shell_integration/zsh'

##
# Paths
#
# In zsh, the $PATH variable is tied to the $path variable.
# This makes the $path variable act like a set.
typeset -U path

##
# My zsh includes
for file in ~/.zsh/includes/*; do
    source "$file"
done

SSH_AUTH_SOCK=/Users/rawkode/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh

_direnv_hook() {
  trap -- '' SIGINT;
  eval "$("${HOMEBREW_PREFIX-/usr/local}/bin/direnv" export zsh)";
  trap - SIGINT;
}

typeset -ag precmd_functions;
if [[ -z ${precmd_functions[(r)_direnv_hook]} ]]; then
  precmd_functions=( _direnv_hook ${precmd_functions[@]} )
fi

typeset -ag chpwd_functions;
if [[ -z ${chpwd_functions[(r)_direnv_hook]} ]]; then
  chpwd_functions=( _direnv_hook ${chpwd_functions[@]} )
fi
