# Plugin Manager
source "${HOME}/.zgenom/zgenom.zsh"
zgenom autoupdate

if ! zgenom saved; then
  # Core Settings
  export HOMEBREW_NO_AUTO_UPDATE=1

  ## Treat $PATH as a set, allows adding new directories to be more
  # code like.
  typeset -U path
  path=("/usr/local/bin" $path)
  path=("/opt/homebrew/bin" $path)
  path=("${HOME}/.local/bin" $path)

  # Expand aliases with space
  typeset -U GLOBALIAS_FILTER_VALUES
  zgenom ohmyzsh plugins/globalias

  ##
  # Always Clear Screen & Run `ls`
  ##
  AUTO_LS_COMMANDS=(eza git-status)

  zgenom load desyncr/auto-ls

  auto-ls-eza () {
    eza -l
    [[ $AUTO_LS_NEWLINE != false ]] && echo ""
  }

  # Temp Sandbox
  alias tmp='cd $(mktemp -d)'

  # Completion/Suggestions
  # zgenom load zsh-users/zsh-autosuggestions
  # zgenom load marlonrichert/zsh-autocomplete
  # zstyle ':autocomplete:*' min-input 1

  ZSH_HIGHLIGHT_HIGHLIGHTERS=( main brackets )
  zgenom load zsh-users/zsh-syntax-highlighting
  zgenom load zdharma-continuum/fast-syntax-highlighting

  # ls
  TREE_IGNORE="cache|log|logs|node_modules|vendor"

  alias ls='eza --group-directories-first'
  alias la='ls -a'
  alias ll='ls --git -l'
  alias lt='ls --tree -D -L 2 -I ${TREE_IGNORE}'
  alias ltt='ls --tree -D -L 3 -I ${TREE_IGNORE}'
  alias lttt='ls --tree -D -L 4 -I ${TREE_IGNORE}'
  alias ltttt='ls --tree -D -L 5 -I ${TREE_IGNORE}'

  GLOBALIAS_FILTER_VALUES=(ls la ll lt ltt lttt lttt $GLOBALIAS_FILTER_VALUES)

  # SSH
  alias bssh="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  alias bscp="scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

  # Development aliases
  alias ghb="cd ${HOME}/Code/src/github.com"
  alias glb="cd ${HOME}/Code/src/gitlab.com"

  for file in ~/.zsh/includes/*; do
      #source "$file"
      zgenom load ${file}
  done

  autoload -Uz compinit && compinit
fi

if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

eval "$(starship init zsh)"
eval "$(direnv hook zsh)"

export TERM=xterm-256color
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

