// Module augmentation for `ctx.exports`/`this.ctx.exports` typing (Cloudflare.Exports).
//
// wrangler.jsonc declares WorkspaceDurableObject/UserDurableObject under `new_sqlite_classes` with
// no explicit `durable_objects` binding — they're reached via `ctx.exports.<ClassName>`, the
// "Workers Exports" mechanism (see cloudflare-os/packages/workshop-backend's identical pattern,
// e.g. `this.ctx.exports.UserDurableObject`). `@cloudflare/workers-types` types this as
// `Cloudflare.Exports`, computed from `Cloudflare.GlobalProps.mainModule` (this file's default
// export shape) and `Cloudflare.GlobalProps.durableNamespaces` (which exports are DOs, so they're
// typed as `DurableObjectNamespace<T>` rather than a plain RPC loopback). Normally `wrangler
// types` generates this file's equivalent (`worker-configuration.d.ts`) at the package root from
// wrangler.jsonc — since this task is scoped to `src/` only, it's hand-written here instead,
// which is equally correct: `wrangler types`' output is exactly this same declaration-merge
// pattern, just autogenerated.

import type * as MainModule from "./index.js"

declare global {
  namespace Cloudflare {
    interface GlobalProps {
      mainModule: typeof MainModule
      durableNamespaces:
        | "WorkspaceDurableObject"
        | "UserDurableObject"
        | "FtsSearchProbeDurableObject"
        | "AutomergeProbeDurableObject"
    }
  }
}

export {}
