apiVersion: argoproj.io/v1alpha1
kind: "Application"
metadata:
  name: teleport
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/gravitational/teleport
    path: examples/chart/teleport-daemonset
    targetRevision: master
    helm:
      version: v3
      releaseName: teleport
      parameters:
        - name: ingress.enabled
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
