[package]
name = "multipass-network"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
hmac = "0.12"
sha2 = "0.10"
rand = "0.8"
mdns-sd = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time"] }
uuid = { version = "1", features = ["serde", "v4"] }
zeroize = "1"
