FROM quay.io/fedora-ostree-desktops/silverblue:41 AS base

ARG IMAGE_NAME="${IMAGE_NAME:-rawkOS}"
ARG IMAGE_VENDOR="${IMAGE_VENDOR:-rawkode}"
ARG IMAGE_FLAVOR="${IMAGE_FLAVOR:-base}"

COPY --from=mirror.gcr.io/denoland/deno:latest /usr/bin/deno /usr/bin/deno

WORKDIR /build
COPY . /build

RUN DENO_DIR=/deno deno run --allow-all build.ts && rm -rf /build

RUN ostree container commit
