apiVersion: getambassador.io/v2
kind: Listener
metadata:
  name: argocd-server-ui
  namespace: argocd
spec:
  port: 443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    selector:
      matchLabels:
        dnsname: argocd
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: argocd-server-ui
  namespace: argocd
  labels:
    dnsname: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory
    email: david@rawkode.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-server-ui
  namespace: argocd
  labels:
    dnsname: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  service: argocd-server:443
  prefix: /
