---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: argocd-server-ui
  labels:
    dnsname: argocd
spec:
  hostname: example.com
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory
    email: david@rawkode.com
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-server-ui
  namespace: argocd
  labels:
    dnsname: argocd
spec:
  service: argocd-server:443
  prefix: /
