apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ingress-domain-injector
spec:
  background: false
  rules:
    - name: environment-details-lookup
      context:
        - name: domain
          configMap:
            namespace: argocd
            name: environment-details
      match:
        resources:
          kinds:
            - getambassador.io/v2/Mapping
          selector:
            matchLabels:
              dnsname: ""
      mutate:
        patchStrategicMerge:
          spec:
            host: "{{request.object.metadata.labels.dnsname}}.{{environment-details-lookup.data.domain}}"
