apiVersion: argoproj.io/v1alpha1
kind: "Application"
metadata:
  name: kyverno
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: management
  project: default
  source:
    repoURL: https://github.com/kyverno/kyverno
    path: charts/kyverno
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
