apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ingress-domain-injector
spec:
  background: false
  rules:
    - name: environment
      context:
        - name: environment
          configMap:
            namespace: argocd
            name: environment-details
      match:
        resources:
          kinds:
            - getambassador.io/v2/Mapping
      mutate:
        patchStrategicMerge:
          spec:
            host: "{{ request.object.metadata.labels.dnsname }}.{{ environment.data.domain }}"
