{
  flake.homeModules.profiles-home =
    { inputs, ... }:
    {
      imports = with inputs.self.homeModules; [
        atuin
        bat
        btop
        carapace
        comma
        cue
        development-bun
        development-dagger
        development-deno
        development-devenv
        development-distrobox
        development-flox
        development-go
        development-kubernetes
        development-moon
        development-nix
        development-podman
        development-python
        development-rust
        direnv
        eza
        fish
        git
        github
        google-cloud
        helix
        htop
        jj
        jq
        just
        lazyjournal
        misc
        nh
        nushell
        pulumi
        ripgrep
        starship
        television
        zellij
        zoxide
      ];
    };
}
