// loro-swift-interop.test.ts
// @enchiridion/worker-vault
//
// The cross-language fixture test plan Risk #1 calls the single most
// important P0 proof point and that, until now, nothing in this codebase
// actually exercised: bytes a REAL `loro-swift` `LoroDoc` produced, decoded
// by a REAL `loro-crdt` `LoroDoc` (via this worker's actual production
// import path, `LoroPageDoc.fromSnapshot` — not a bare `new LoroDoc()`
// bypass), and vice versa. `loro-storage.test.ts` covers WASM<->WASM
// round-trips only; this file is the missing WASM<->Swift half.
//
// Fixtures live at
// packages/graph-core/src/__fixtures__/loro-interop/{swift,ts}-exported-
// snapshot.{bin,expected.json} — checked-in, one-time-generated bytes plus a
// JSON sidecar describing the exact decoded state (text, rich-text delta
// runs, map values) so the consuming side asserts semantically, not just
// "it imported without throwing". packages/graph-core is the natural shared
// location: it's the TS-mirror package in the monorepo layout, sitting next
// to both apps/swift and workers/vault without either needing to depend on
// the other's source tree to find the fixture.
//
// Regeneration:
//   - ts-exported-snapshot.{bin,expected.json}: this file, generator test
//     below, gated behind `GENERATE_LORO_FIXTURES=1` so a normal `bun test`
//     never rewrites a checked-in fixture (Loro assigns each `LoroDoc` a
//     fresh random peer ID, so an unconditional re-run would change the
//     fixture's raw bytes — though not its decoded meaning — on every test
//     invocation). Run:
//       GENERATE_LORO_FIXTURES=1 bun test src/loro-swift-interop.test.ts
//     from workers/vault/.
//   - swift-exported-snapshot.{bin,expected.json}: generated on the Swift
//     side — see the header comment on
//     apps/swift/Tests/EnchiridionSyncTests/GenerateLoroInteropFixtures.swift
//     for its regeneration command.

import { describe, expect, test } from "bun:test";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Delta } from "loro-crdt/bundler";
import { decodeVersionVector, LoroPageDoc } from "./loro-storage";

const FIXTURE_DIR = join(
  import.meta.dir,
  "..",
  "..",
  "..",
  "packages",
  "graph-core",
  "src",
  "__fixtures__",
  "loro-interop"
);

/** The full expected-decoded-state sidecar shape, shared by both fixture
 *  directions. Whichever language DIDN'T generate a given fixture asserts
 *  its own real decode of the fixture bytes against this JSON, field by
 *  field. `bodyDelta` reuses `loro-crdt`'s own `Delta<string>` shape (as
 *  produced by `LoroText.toDelta()` on this side and
 *  `LoroText.getRichtextValue()` on the Swift side — both wrap the
 *  identical underlying Loro rich-text representation) rather than a
 *  hand-rolled {key,start,end} mark-range scheme that would need
 *  separately-maintained offset arithmetic on both sides. A run's
 *  `attributes` key is omitted entirely (not `null`/`{}`) when no marks are
 *  active — confirmed empirically against the real `loro-crdt` package
 *  before this shape was fixed here. */
interface LoroInteropFixtureExpectation {
  generatedBy: "swift" | "typescript";
  bodyContainer: string;
  objectMetadataContainer: string;
  bodyText: string;
  bodyDelta: Delta<string>[];
  objectMetadata: Record<string, unknown>;
}

function readFixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(join(FIXTURE_DIR, name)));
}

function readExpectation(name: string): LoroInteropFixtureExpectation {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, name), "utf8"));
}

/** Builds the TS->Swift fixture doc. Distinct text/marks/map values from the
 *  Swift->TS fixture (see GenerateLoroInteropFixtures.swift) so a test
 *  reading the wrong fixture file by accident fails loudly instead of
 *  coincidentally matching. Mark positions are computed via `indexOf`
 *  rather than hand-counted character offsets, to avoid an off-by-one
 *  slipping into the fixture's ground truth. */
function buildTsFixtureDoc(): { page: LoroPageDoc; expectation: LoroInteropFixtureExpectation } {
  const page = LoroPageDoc.create();
  const bodyText = "Hi from TypeScript, meet Swift";
  const text = page.text("body");
  text.insert(0, bodyText);

  const boldStart = bodyText.indexOf("TypeScript");
  const boldEnd = boldStart + "TypeScript".length;
  text.mark({ start: boldStart, end: boldEnd }, "bold", true);

  const refStart = bodyText.lastIndexOf("Swift");
  const refEnd = refStart + "Swift".length;
  text.mark({ start: refStart, end: refEnd }, "pageReference", "person_ts_generator_fixture");

  const map = page.map("objectMetadata");
  map.set("kind", "interop-fixture");
  map.set("version", 1);
  map.set("verified", true);

  page.commit();

  const expectation: LoroInteropFixtureExpectation = {
    generatedBy: "typescript",
    bodyContainer: "body",
    objectMetadataContainer: "objectMetadata",
    bodyText,
    bodyDelta: text.toDelta(),
    objectMetadata: page.mapShallowValue("objectMetadata"),
  };

  return { page, expectation };
}

const SHOULD_GENERATE = process.env.GENERATE_LORO_FIXTURES === "1";

describe("Loro Swift <-> TypeScript interop fixtures (plan Risk #1 / P0 exit criterion)", () => {
  test.skipIf(!SHOULD_GENERATE)(
    "generates ts-exported-snapshot.bin + .expected.json (one-time; see header comment)",
    () => {
      const { page, expectation } = buildTsFixtureDoc();
      mkdirSync(FIXTURE_DIR, { recursive: true });
      writeFileSync(join(FIXTURE_DIR, "ts-exported-snapshot.bin"), page.exportSnapshot());
      writeFileSync(
        join(FIXTURE_DIR, "ts-exported-snapshot.expected.json"),
        JSON.stringify(expectation, null, 2) + "\n"
      );
    }
  );

  test("ts-exported-snapshot.bin (this fixture's own JSON sidecar is self-consistent)", () => {
    const bytes = readFixture("ts-exported-snapshot.bin");
    const expected = readExpectation("ts-exported-snapshot.expected.json");

    const page = LoroPageDoc.fromSnapshot(bytes);
    expect(page.textContent(expected.bodyContainer)).toBe(expected.bodyText);
    expect(page.text(expected.bodyContainer).toDelta()).toEqual(expected.bodyDelta);
    expect(page.mapShallowValue(expected.objectMetadataContainer)).toEqual(expected.objectMetadata);
  });

  test("swift-exported-snapshot.bin imports via the real loro-storage.ts path (LoroPageDoc.fromSnapshot) and decodes to the expected state", () => {
    const bytes = readFixture("swift-exported-snapshot.bin");
    const expected = readExpectation("swift-exported-snapshot.expected.json");

    expect(expected.generatedBy).toBe("swift");

    // The real production import path — LoroPageDoc.fromSnapshot, exactly
    // what doc-store.ts calls when hydrating a doc from a stored snapshot —
    // not a bypass straight to `new LoroDoc()`.
    const page = LoroPageDoc.fromSnapshot(bytes);

    expect(page.textContent(expected.bodyContainer)).toBe(expected.bodyText);
    expect(page.text(expected.bodyContainer).toDelta()).toEqual(expected.bodyDelta);
    expect(page.mapShallowValue(expected.objectMetadataContainer)).toEqual(expected.objectMetadata);

    // Version-vector shape: Swift's LoroDoc assigns its own random peer ID
    // on write (LoroEngine.swift never calls setPeerId, same as this
    // worker's default — see loro-storage.ts's "Peer ID" header note), so
    // exact peer IDs can't be asserted cross-language. What CAN be asserted
    // is that the WASM side decodes a real, non-empty version vector out of
    // Swift-produced bytes and that it survives an encode/decode round trip
    // — proving the version-vector wire format itself is shared, which is
    // exactly what the sync protocol's version-vector exchange depends on.
    const vv = page.versionVector();
    const encoded = vv.encode();
    expect(encoded.length).toBeGreaterThan(0);
    const decoded = decodeVersionVector(encoded);
    expect(decoded.encode()).toEqual(encoded);
  });
});
