name: opengraph-deploy

on:
  push:
    branches:
      - main
    paths:
      - websites/opengraph.rawkode.dev/deploy/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
        working-directory: websites/opengraph.rawkode.dev/deploy
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: production
          work-dir: websites/opengraph.rawkode.dev/deploy
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
