name: plausible.rawkode.dev

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - websites/plausible.rawkode.dev/**
  pull_request:
    paths:
      - websites/plausible.rawkode.dev/**
  schedule:
    - cron: "6 6 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: plausible.rawkode.dev
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./websites/plausible.rawkode.dev
          github-comment: false
