name: short-links

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - projects/short-links/**
  schedule:
    - cron: "6 6 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
        working-directory: projects/short-links
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: production
          refresh: true
          work-dir: projects/short-links
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - run: "echo ${SHORT_LINKS_CONNECTION_STRING} && npx prisma db push"
        working-directory: projects/short-links/worker
        env:
          SHORT_LINKS_CONNECTION_STRING: ${{ secrets.SHORT_LINKS_CONNECTION_STRING }}
