apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik
    role: ingress-controller
  name: traefik-ingress-controller
spec:
  selector:
    app: traefik
    role: ingress-controller
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
